#!/bin/sh
mydir=$(dirname "$1") #folder of .doom file
czdir=$(dirname "$0") #get czdoom's folder
cd "$mydir"
doomfile="`cat "$1" | cut -d "|" -f 1`" #assume the input might be trying something sketchy and remove pipes
$czdir/czdoom $doomfile